#!/usr/bin/python3
# SPDX-FileCopyrightText:2023 Ryohei Tsuchida
# SPDX-License-Identifier:BSD-3-Clau

import sys
from decimal import Decimal, getcontext

getcontext().prec = 10

def main():
    if len(sys.argv) > 1:
        nums = [Decimal(e) for e in sys.argv[1:]]
    else:
        nums = [Decimal(line) for line in sys.stdin]

    print(sum(nums))

if __name__ == '__main__':

    main()
