#!/usr/bin/python3
# SPDX-FileCopyrightText:2023 Ryohei Tsuchida
# SPDX-License-Identifier:BSD-3-Clause

import sys

def get_numbers():
    try:
        return [float(e) for e in sys.argv[1:]]
    except ValueError:
        print("Error: Invalid command-line arguments. Please provide valid numbers.")
        sys.exit(1)

def read_numbers_from_input():
    try:
        return [float(line) for line in sys.stdin]
    except ValueError:
        print("Error: Invalid input. Please provide valid numbers.")
        sys.exit(1)

def main():
    if len(sys.argv) > 1:
        nums = get_numbers()
    else:
        nums = read_numbers_from_input()

    print(sum(nums))

if __name__ == "__main__":
    main()
